[package]
name = "mx-docsrs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "docsrs"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
cargo_metadata = "0.23.0"
anyhow = "1.0.99"
