[package]
name = "rustdoc-fmt"
version = "0.1.0"
edition.workspace = true

[dependencies]
colored.workspace = true
syntect.workspace = true
terminal-colorsaurus.workspace = true
pulldown-cmark.workspace = true
